print ("Olá mundo !!")
print ("Olá de novo")
print ("Eu gosto de digitar isso")
print ("Isso é divertido")
print ("Yay ! Imprimindo.")
print ("Eu preferia que você 'não'.")
print ("I 'disse' não toque nisso.")